(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='digiexpress.timeStudy.v1', PROJECTS='digiexpress.timeStudy.projects.v1';
const state={projectInfo:{},tasks:[],records:[],dynamicField:null,activeProjectId:null,editingProjectId:null,currentTask:null,taskStart:null,pauseStarted:null,totalPauseMs:0,pieceCount:1,workerCount:1,rating:1,paused:false,selectedCustom:''};
let tick=null;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.remove('show'),2200)}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function gregorianToJalali(y,m,d){const g=[0,31,59,90,120,151,181,212,243,273,304,334];let gy=y-1600,gm=m-1,gd=d-1;let n=365*gy+Math.floor((gy+3)/4)-Math.floor((gy+99)/100)+Math.floor((gy+399)/400)+g[gm]+gd;if(gm>1&&((y%4===0&&y%100!==0)||y%400===0))n++;let j=n-79,cycles=Math.floor(j/12053);j%=12053;let jy=979+33*cycles+4*Math.floor(j/1461);j%=1461;if(j>=366){jy+=Math.floor((j-1)/365);j=(j-1)%365}let jm,jd;if(j<186){jm=1+Math.floor(j/31);jd=1+j%31}else{jm=7+Math.floor((j-186)/30);jd=1+(j-186)%30}return `${String(jy).padStart(4,'0')}${String(jm).padStart(2,'0')}${String(jd).padStart(2,'0')}`}
function todayJ(){const n=new Date();return gregorianToJalali(n.getFullYear(),n.getMonth()+1,n.getDate())}
function normalizeDate(v){const digits=String(v||'').replace(/\D/g,'');if(digits.length!==8)return digits;const y=+digits.slice(0,4),m=+digits.slice(4,6),d=+digits.slice(6);return y>=1700?gregorianToJalali(y,m,d):digits}
function saveSession(){localStorage.setItem(STORE,JSON.stringify({projectInfo:state.projectInfo,tasks:state.tasks,records:state.records,dynamicField:state.dynamicField,activeProjectId:state.activeProjectId}))}
function loadSession(){try{const x=JSON.parse(localStorage.getItem(STORE)||'{}');Object.assign(state,{projectInfo:x.projectInfo||{},tasks:x.tasks||[],records:x.records||[],dynamicField:x.dynamicField||null,activeProjectId:x.activeProjectId||null})}catch{}}
function loadProjects(){try{const x=JSON.parse(localStorage.getItem(PROJECTS)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveProjects(p){localStorage.setItem(PROJECTS,JSON.stringify(p))}
function nav(name){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));const app=document.querySelector('.ts-app');app.classList.toggle('timer-mode',name==='timer');if(name==='home'||name==='timer')$('#projectChip').classList.add('hidden');else if(state.projectInfo.project_name){$('#projectChip').textContent=state.projectInfo.project_name;$('#projectChip').classList.remove('hidden')}if(name==='projects')renderProjects();if(name==='tasks')renderTasks();if(name==='timer')renderTimerMeta();if(name!=='timer')app.classList.remove('paused-mode');app.scrollTop=0}
$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
function resetNewProject(){state.projectInfo={};state.tasks=[];state.records=[];state.dynamicField=null;state.activeProjectId=null;state.editingProjectId=null;$('#projectName').value='';$('#stationName').value='';$('#projectDate').value=todayJ();$('#specialistName').value='';$('#customFieldName').value='';$('#customFieldValues').value='';saveSession()}
$$('[data-go="project"]').forEach(b=>b.addEventListener('click',()=>{if(b.closest('[data-screen="home"]'))resetNewProject()}));
$('#projectForm').onsubmit=e=>{e.preventDefault();state.projectInfo={project_name:$('#projectName').value.trim(),station_name:$('#stationName').value.trim(),date:normalizeDate($('#projectDate').value),specialist_name:$('#specialistName').value.trim()};if(!state.projectInfo.project_name||!state.projectInfo.station_name||state.projectInfo.date.length!==8)return toast('Please complete project name, station and date.');nav('tasks')};
$('#addTask').onclick=()=>{const v=$('#taskNameInput').value.trim();if(!v)return;if(state.tasks.includes(v))return toast('Task already exists.');state.tasks.push(v);$('#taskNameInput').value='';renderTasks()};
$('#taskNameInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#addTask').click()}});
function renderTasks(){$('#taskList').innerHTML=state.tasks.length?state.tasks.map((t,i)=>`<div class="task-item"><span>${esc(t)}</span><button data-del-task="${i}" title="Delete">×</button></div>`).join(''):'<div class="project-meta">No tasks defined.</div>';$$('[data-del-task]').forEach(b=>b.onclick=()=>{state.tasks.splice(+b.dataset.delTask,1);renderTasks()})}
function collectDynamic(){const n=$('#customFieldName').value.trim(),vals=$('#customFieldValues').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return n&&vals.length?{name:n,values:vals}:null}
function saveProjectDefinition(){let projects=loadProjects();const id=state.editingProjectId||state.activeProjectId||uid();const def={id,project_info:{...state.projectInfo,date:normalizeDate(state.projectInfo.date)},tasks:[...state.tasks],dynamic_field:state.dynamicField,updated_at:new Date().toISOString()};const idx=projects.findIndex(p=>p.id===id);if(idx>=0)projects[idx]=def;else projects.push(def);saveProjects(projects);state.activeProjectId=id;state.editingProjectId=null;saveSession();return id}
$('#startStudy').onclick=()=>{if(!state.tasks.length)return toast('Please define at least one task.');state.dynamicField=collectDynamic();saveProjectDefinition();state.records=[];startTimerUI();nav('timer')};
function renderProjects(){const p=loadProjects();$('#savedProjects').innerHTML=p.length?p.map(x=>`<div class="project-row"><div><strong>${esc(x.project_info?.project_name||'Untitled')}</strong><div class="project-meta">${esc(x.project_info?.station_name||'')} · ${esc(x.project_info?.date||'')}</div></div><div class="project-actions"><button class="primary-btn" data-start-project="${x.id}">Start</button><button class="secondary" data-edit-project="${x.id}">Edit</button><button class="secondary" data-delete-project="${x.id}">Delete</button></div></div>`).join(''):'<div class="card project-meta">No saved projects.</div>';$$('[data-start-project]').forEach(b=>b.onclick=()=>loadProject(b.dataset.startProject,false));$$('[data-edit-project]').forEach(b=>b.onclick=()=>loadProject(b.dataset.editProject,true));$$('[data-delete-project]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this saved project?'))return;saveProjects(loadProjects().filter(x=>x.id!==b.dataset.deleteProject));renderProjects()})}
function loadProject(id,edit){const p=loadProjects().find(x=>x.id===id);if(!p)return;state.projectInfo={...p.project_info};state.tasks=[...(p.tasks||[])];state.dynamicField=p.dynamic_field||null;state.activeProjectId=id;state.editingProjectId=edit?id:null;state.records=[];if(edit){$('#projectName').value=state.projectInfo.project_name||'';$('#stationName').value=state.projectInfo.station_name||'';$('#projectDate').value=state.projectInfo.date||todayJ();$('#specialistName').value=state.projectInfo.specialist_name||'';$('#customFieldName').value=state.dynamicField?.name||'';$('#customFieldValues').value=(state.dynamicField?.values||[]).join('\n');nav('project')}else{startTimerUI();nav('timer')}}
function choiceButton(label,kind,value,onClick){const b=document.createElement('button');b.className=`choice-btn ${kind}`;b.textContent=label;b.type='button';b.dataset.value=value;b.onclick=()=>onClick(value,b);return b}
function setSelected(container,b){container.querySelectorAll('.choice-btn').forEach(x=>x.classList.remove('selected'));if(b)b.classList.add('selected')}
function buildChoices(){const p=$('#pieceButtons');p.innerHTML='';for(let i=1;i<=7;i++)p.append(choiceButton(i,'piece',i,(v,b)=>{state.pieceCount=+v;$('#pieceCustom').value='';setSelected(p,b)}));const pi=document.createElement('input');pi.id='pieceCustom';pi.className='choice-custom';pi.type='number';pi.min=1;pi.placeholder='Custom';pi.oninput=()=>{if(+pi.value>0){state.pieceCount=+pi.value;setSelected(p,null)}};p.append(pi);
 const w=$('#workerButtons');w.innerHTML='';for(let i=1;i<=3;i++)w.append(choiceButton(i,'worker',i,(v,b)=>{state.workerCount=+v;$('#workerCustom').value='';setSelected(w,b)}));const wi=document.createElement('input');wi.id='workerCustom';wi.className='choice-custom';wi.type='number';wi.min=1;wi.placeholder='Custom';wi.oninput=()=>{if(+wi.value>0){state.workerCount=+wi.value;setSelected(w,null)}};w.append(wi);
 const r=$('#ratingButtons');r.innerHTML='';[80,90,100,110,120].forEach(n=>r.append(choiceButton(n,'rating',n,(v,b)=>{state.rating=+v/100;$('#ratingCustom').value='';setSelected(r,b)})));const ri=document.createElement('input');ri.id='ratingCustom';ri.className='choice-custom';ri.type='number';ri.min=1;ri.placeholder='Custom';ri.oninput=()=>{if(+ri.value>0){state.rating=+ri.value/100;setSelected(r,null)}};r.append(ri);setSelected(p,p.querySelector('[data-value="1"]'));setSelected(w,w.querySelector('[data-value="1"]'));setSelected(r,r.querySelector('[data-value="100"]'))}
function buildRuntimeCustom(){const c=$('#customRuntime');c.innerHTML='';state.selectedCustom='';if(!state.dynamicField?.name||!state.dynamicField.values?.length){c.classList.add('hidden');return}c.classList.remove('hidden');const title=document.createElement('div');title.className='section-label';title.textContent=state.dynamicField.name;c.append(title);const grid=document.createElement('div');grid.className='choice-grid';state.dynamicField.values.slice(0,10).forEach(v=>grid.append(choiceButton(v,'piece',v,(val,b)=>{state.selectedCustom=String(val);setSelected(grid,b)})));c.append(grid)}
function buildTimerTasks(){const g=$('#timerTasks');g.innerHTML='';state.tasks.forEach(t=>{const b=document.createElement('button');b.type='button';b.className='task-btn';b.textContent=t;b.dataset.task=t;b.onclick=()=>selectTask(t);g.append(b)})}
function startTimerUI(){stopTick();state.currentTask=null;state.taskStart=null;state.pauseStarted=null;state.totalPauseMs=0;state.pieceCount=1;state.workerCount=1;state.rating=1;state.paused=false;document.querySelector('.ts-app').classList.remove('paused-mode');$('#description').value='';$('#pauseBtn').textContent='Pause';$('#timerDisplay').textContent='00:00';$('#currentTask').textContent='Current Task: —';buildChoices();buildRuntimeCustom();buildTimerTasks();startTick()}
function renderTimerMeta(){$('#timerProject').textContent=`${state.projectInfo.project_name||''} · ${state.projectInfo.station_name||''} · ${normalizeDate(state.projectInfo.date||'')}`}
function startTick(){stopTick();tick=setInterval(()=>{if(!state.taskStart||state.paused)return;const ms=Date.now()-state.taskStart-state.totalPauseMs;$('#timerDisplay').textContent=formatClock(ms)},100)}function stopTick(){if(tick){clearInterval(tick);tick=null}}
function formatClock(ms){const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60);return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function finishCurrent(endMs){if(!state.currentTask||!state.taskStart)return;let paused=state.totalPauseMs;if(state.paused&&state.pauseStarted)paused+=endMs-state.pauseStarted;const actual=Math.max(0,(endMs-state.taskStart-paused)/1000),per=state.pieceCount>0?actual/state.pieceCount:actual;const st=new Date(state.taskStart),et=new Date(endMs);const rec={project_name:state.projectInfo.project_name,station_name:state.projectInfo.station_name,date:normalizeDate(state.projectInfo.date),specialist_name:state.projectInfo.specialist_name||'N/A',study_date:todayJ(),task_name:state.currentTask,start_time:st.toTimeString().slice(0,8),end_time:et.toTimeString().slice(0,8),duration_seconds:actual,duration_formatted:new Date(actual*1000).toISOString().slice(11,19),piece_count:state.pieceCount,worker_count:state.workerCount,time_per_piece:per,performance_rating:state.rating,standard_time:per*state.rating,description:$('#description').value.trim()};if(state.dynamicField?.name&&state.selectedCustom){rec.dynamic_field_name=state.dynamicField.name;rec.dynamic_field_value=state.selectedCustom}state.records.push(rec);$('#description').value='';saveSession()}
function taskFeedback(){try{navigator.vibrate?.(25)}catch{}try{const A=window.AudioContext||window.webkitAudioContext;if(A){const c=new A(),o=c.createOscillator(),g=c.createGain();o.frequency.value=880;g.gain.value=.04;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.08);o.onended=()=>c.close()}}catch{}}
function selectTask(name){if(state.paused)return toast('Continue the study before switching tasks.');taskFeedback();const now=Date.now();finishCurrent(now);state.currentTask=name;state.taskStart=now;state.totalPauseMs=0;state.pauseStarted=null;$('#currentTask').textContent=`Current Task: ${name}`;$$('.task-btn').forEach(b=>b.classList.toggle('selected',b.dataset.task===name));$('#timerDisplay').textContent='00:00';saveSession()}
$('#pauseBtn').onclick=()=>{if(!state.currentTask)return toast('Select a task first.');const app=document.querySelector('.ts-app');if(!state.paused){state.paused=true;state.pauseStarted=Date.now();$('#pauseBtn').textContent='Continue';$('#currentTask').textContent='Status: PAUSED';app.classList.add('paused-mode')}else{state.totalPauseMs+=Date.now()-state.pauseStarted;state.pauseStarted=null;state.paused=false;$('#pauseBtn').textContent='Pause';$('#currentTask').textContent=`Current Task: ${state.currentTask}`;app.classList.remove('paused-mode')}}
$('#endStudy').onclick=()=>modal('End Time Study','Are you sure you want to end the time study?',[['No','secondary',closeModal],['Yes','danger-btn',()=>{closeModal();finishCurrent(Date.now());stopTick();state.currentTask=null;state.paused=false;document.querySelector('.ts-app').classList.remove('paused-mode');saveSession();modal('Completed','Time study completed successfully.',[['Home','secondary',()=>{closeModal();nav('home')}],['New Project','primary-btn',()=>{closeModal();resetNewProject();nav('project')}],['Save Excel','primary-btn',()=>{exportRecords();closeModal()}]])}]])
function modal(title,body,actions){$('#modalTitle').textContent=title;$('#modalBody').textContent=body;const a=$('#modalActions');a.innerHTML='';actions.forEach(([text,cls,fn])=>{const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;a.append(b)});$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
$('#homeAbout').onclick=()=>modal('About','Time Study Assistant · Production Line Time Study Software · Developed by Naser Habibifar · 2026',[['Close','primary-btn',closeModal]])
// --- minimal genuine XLSX writer (ZIP store + inline strings) ---
const crcTable=(()=>{let t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function u16(n){return [n&255,(n>>>8)&255]}function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function zipStore(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;for(const [name,content] of Object.entries(files)){const nb=enc.encode(name),data=typeof content==='string'?enc.encode(content):content,crc=crc32(data);const local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(nb.length),...u16(0),...nb]);parts.push(local,data);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(nb.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...nb]));offset+=local.length+data.length}const centralOffset=offset,centralSize=central.reduce((a,b)=>a+b.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(central.length),...u16(central.length),...u32(centralSize),...u32(centralOffset),...u16(0)]);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function colName(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function sheetXml(rows){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((r,ri)=>`<row r="${ri+1}">${r.map((v,ci)=>{const ref=colName(ci+1)+(ri+1);if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}"><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`}).join('')}</row>`).join('')}</sheetData></worksheet>`}
function buildXlsx(sheets){const files={'[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`,'_rels/.rels':`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`,'xl/_rels/workbook.xml.rels':`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`};sheets.forEach((s,i)=>files[`xl/worksheets/sheet${i+1}.xml`]=sheetXml(s.rows));return zipStore(files)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function exportRecords(){if(!state.records.length)return toast('No data to export.');const headers=['Project Name','Station Name','Date','Specialist','Study Date','Task Name','Start Time','End Time','Duration (sec)','Duration (formatted)','Piece Count','Worker Count','Time per Piece (sec)','Performance Rating','Standard Time (sec)','Description'];if(state.dynamicField?.name)headers.push(state.dynamicField.name);const rows=[headers,...state.records.map(r=>[r.project_name,r.station_name,r.date,r.specialist_name,r.study_date,r.task_name,r.start_time,r.end_time,+r.duration_seconds.toFixed(2),r.duration_formatted,r.piece_count,r.worker_count,+r.time_per_piece.toFixed(2),+r.performance_rating.toFixed(2),+r.standard_time.toFixed(2),r.description,...(state.dynamicField?.name?[r.dynamic_field_value||'']:[])])];const name=(state.projectInfo.project_name||'time_study').replace(/[^\w\-]+/g,'_');download(buildXlsx([{name:'Time Study',rows}]),`${name}_${new Date().toISOString().replace(/[:T]/g,'-').slice(0,19)}.xlsx`)}
$('#homeExport').onclick=exportRecords;
function exportProjectDefs(){const p=loadProjects();if(!p.length)return toast('No saved projects.');const projects=[['Project ID','Project Name','Station Name','Date','Specialist Name','Updated At']],tasks=[['Project ID','Task Order','Task Name']],fields=[['Project ID','Field Order','Field Name','Value Order','Field Value']];p.forEach(x=>{projects.push([x.id,x.project_info?.project_name||'',x.project_info?.station_name||'',x.project_info?.date||'',x.project_info?.specialist_name||'',x.updated_at||'']);(x.tasks||[]).forEach((t,i)=>tasks.push([x.id,i+1,t]));(x.dynamic_field?.values||[]).forEach((v,i)=>fields.push([x.id,1,x.dynamic_field.name,i+1,v]))});download(buildXlsx([{name:'Projects',rows:projects},{name:'Tasks',rows:tasks},{name:'Custom Fields',rows:fields}]),`time_study_projects_${Date.now()}.xlsx`)}
$('#exportProjects').onclick=exportProjectDefs;
function readZipStore(buf){const b=new Uint8Array(buf),dec=new TextDecoder(),files={};let p=0;while(p+30<b.length&&b[p]===0x50&&b[p+1]===0x4b&&b[p+2]===0x03&&b[p+3]===0x04){const method=b[p+8]|b[p+9]<<8,cs=b[p+18]|b[p+19]<<8|b[p+20]<<16|b[p+21]<<24,ns=b[p+26]|b[p+27]<<8,es=b[p+28]|b[p+29]<<8;const name=dec.decode(b.slice(p+30,p+30+ns)),start=p+30+ns+es;if(method!==0)throw Error('Only project files exported by this app can be imported.');files[name]=dec.decode(b.slice(start,start+cs));p=start+cs}return files}
function parseSheet(xml){const doc=new DOMParser().parseFromString(xml,'application/xml'),rows=[];doc.querySelectorAll('sheetData > row').forEach(row=>{const vals=[];row.querySelectorAll('c').forEach(c=>{const m=(c.getAttribute('r')||'A1').match(/[A-Z]+/),letters=m?m[0]:'A';let idx=0;for(const ch of letters)idx=idx*26+ch.charCodeAt(0)-64;const t=c.getAttribute('t');vals[idx-1]=t==='inlineStr'?(c.querySelector('is t')?.textContent||''):(c.querySelector('v')?.textContent||'')});rows.push(vals)});return rows}
$('#importProjects').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.name.endsWith('.json')){const x=JSON.parse(await f.text());if(!Array.isArray(x))throw Error('Invalid file');saveProjects(x)}else{const files=readZipStore(await f.arrayBuffer()),pr=parseSheet(files['xl/worksheets/sheet1.xml']||''),tr=parseSheet(files['xl/worksheets/sheet2.xml']||''),fr=parseSheet(files['xl/worksheets/sheet3.xml']||'');const map={};pr.slice(1).forEach(r=>{if(!r[0])return;map[r[0]]={id:r[0],project_info:{project_name:r[1]||'',station_name:r[2]||'',date:normalizeDate(r[3]||''),specialist_name:r[4]||''},tasks:[],dynamic_field:null,updated_at:r[5]||new Date().toISOString()}});tr.slice(1).sort((a,b)=>(+a[1]||0)-(+b[1]||0)).forEach(r=>{if(map[r[0]]&&r[2])map[r[0]].tasks.push(r[2])});const fg={};fr.slice(1).forEach(r=>{if(!map[r[0]]||!r[2])return;(fg[r[0]]||(fg[r[0]]={name:r[2],values:[]})).values.push(r[4]||'')});Object.entries(fg).forEach(([id,v])=>map[id].dynamic_field=v);const existing=Object.fromEntries(loadProjects().map(x=>[x.id,x]));Object.assign(existing,map);saveProjects(Object.values(existing))}renderProjects();toast('Projects imported.')}catch(err){toast(err.message||'Import failed.')}finally{e.target.value=''}};
loadSession();$('#projectDate').value=state.projectInfo.date||todayJ();renderTasks();
})();
