
const DATA='../data/DX_Polygons.json?v=91';
let rows=[],shown=[],pointHits=[],searchedPoint=null,sortKey='name',sortDir=1;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=L.map('map',{zoomControl:true}).setView([32,51],6), polygons=L.layerGroup().addTo(map), points=L.layerGroup().addTo(map);
const DigiexpressTileLayer=L.TileLayer.extend({createTile(coords,done){const tile=document.createElement('img');L.DomEvent.on(tile,'load',L.Util.bind(this._tileOnLoad,this,done,tile));L.DomEvent.on(tile,'error',L.Util.bind(this._tileOnError,this,done,tile));tile.alt='';tile.setAttribute('role','presentation');tile.referrerPolicy='no-referrer';tile.src=this.getTileUrl(coords);return tile;}});
const baseTiles=new DigiexpressTileLayer('https://osm.digiexpress.ir/tile/{z}/{x}/{y}.png',{maxZoom:19});baseTiles.addTo(map);baseTiles.on('tileerror',e=>console.warn('OSM Digiexpress tile failed',e?.tile?.src||''));
function natureLabel(n){return ({1:'Normal',2:'Medium',3:'Large',4:'Barbari',5:'Business',6:'Fast'})[Number(n)]||String(n??'-')}
function polyColor(n){return ({1:'#1976d2',2:'#16a34a',3:'#7c3aed',4:'#F79009',5:'#d946ef',6:'#0891b2'})[Number(n)]||'#64748b'}
function cleanSubmit(v){return String(v||'').replace(/^EXPRESS\s+/i,'').trim()||'-'}
function makeFilter(host, values, cls){host.innerHTML=values.map(v=>`<label class="filter-chip"><input type="checkbox" class="${cls}" value="${esc(v)}"><span>${esc(v)}</span></label>`).join('');host.querySelectorAll('input').forEach(x=>x.addEventListener('change',applyFilters))}
function selected(cls){return [...document.querySelectorAll('.'+cls+':checked')].map(x=>x.value)}
function pass(r){const ts=selected('f-type'),ds=selected('f-district'),ss=selected('f-submit'),as=selected('f-active');if(ts.length&&!ts.includes(natureLabel(r.natureId)))return false;if(ds.length&&!ds.some(x=>String(r.district||'').startsWith(x)))return false;if(ss.length&&!ss.includes(cleanSubmit(r.submitType)))return false;const av=Number(r.active)===1?'YES':'NO';if(as.length&&!as.includes(av))return false;return true}
function draw(list,fit=false){polygons.clearLayers();list.forEach(r=>(r.coordinates||[]).forEach(part=>{if(!Array.isArray(part)||part.length<3)return;const poly=L.polygon(part,{color:polyColor(r.natureId),weight:2,fillOpacity:.22}).addTo(polygons);poly.bindPopup(`<b>${esc(r.name)}</b><br>ID: ${esc(r.dcId)}<br>IATA: ${esc(r.iata||'-')}<br>Type: ${esc(natureLabel(r.natureId))}<br>Time Scope: ${esc(r.timeScope||'-')}`)}));if(searchedPoint)L.marker(searchedPoint).addTo(points);if(fit){const b=polygons.getBounds();if(b.isValid())map.fitBounds(b,{padding:[12,12]})}}
function render(){const q=$('#search').value.trim().toLocaleLowerCase();let a=(pointHits.length?pointHits:shown).filter(r=>!q||[r.name,r.dcId,r.iata,r.district,r.timeScope,cleanSubmit(r.submitType),natureLabel(r.natureId)].join(' ').toLocaleLowerCase().includes(q));a=[...a].sort((x,y)=>String(x[sortKey]??'').localeCompare(String(y[sortKey]??''),undefined,{numeric:true})*sortDir);$('#count').textContent=`${a.length} polygon${a.length===1?'':'s'}`;$('#results').innerHTML=a.length?`<table><thead><tr><th data-key="name">Name</th><th data-key="dcId">ID</th><th data-key="natureId">Type</th><th data-key="iata">IATA</th><th data-key="timeScope">Time Scope</th></tr></thead><tbody>${a.map(r=>`<tr data-id="${esc(r.dcId)}" data-name="${esc(r.name)}"><td>${esc(r.name)}</td><td>${esc(r.dcId)}</td><td>${esc(natureLabel(r.natureId))}</td><td>${esc(r.iata||'-')}</td><td>${esc(r.timeScope||'-')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No polygons found.</div>';document.querySelectorAll('th[data-key]').forEach(h=>h.onclick=()=>{sortKey=h.dataset.key;sortDir*=-1;render()});document.querySelectorAll('tbody tr').forEach(tr=>tr.onclick=()=>focusPolygon(tr.dataset.id,tr.dataset.name))}
function applyFilters(){shown=rows.filter(pass);pointHits=[];draw(shown,true);render()}
function focusPolygon(id,name){const r=rows.find(x=>String(x.dcId)===String(id)&&String(x.name)===String(name))||rows.find(x=>String(x.dcId)===String(id));if(!r)return;polygons.clearLayers();(r.coordinates||[]).forEach(part=>L.polygon(part,{color:'#e11d48',weight:4,fillOpacity:.34}).addTo(polygons));const b=polygons.getBounds();if(b.isValid())map.fitBounds(b,{padding:[20,20]})}
function checkPoint(){const p=$('#latlon').value.split(',').map(x=>Number(x.trim()));if(p.length!==2||p.some(Number.isNaN)){$('#pointStatus').textContent='Use format: latitude, longitude';$('#pointStatus').className='status error';return}const [lat,lon]=p;searchedPoint=[lat,lon];points.clearLayers();L.marker(searchedPoint).addTo(points);const pt=turf.point([lon,lat]);pointHits=shown.filter(r=>(r.coordinates||[]).some(part=>{try{return turf.booleanPointInPolygon(pt,turf.polygon([[...part.map(c=>[c[1],c[0]])]]))}catch{return false}}));draw(shown,false);L.marker(searchedPoint).addTo(points);pointHits.forEach(r=>(r.coordinates||[]).forEach(part=>L.polygon(part,{color:'#e11d48',weight:4,fillOpacity:.32}).addTo(polygons)));$('#pointStatus').textContent=pointHits.length?`${pointHits.length} matching polygon(s)`:'No polygon contains this point.';$('#pointStatus').className='status '+(pointHits.length?'ok':'error');render();if(pointHits.length){const b=polygons.getBounds();if(b.isValid())map.fitBounds(b,{padding:[20,20]})}else map.setView([lat,lon],14)}
function reset(){document.querySelectorAll('.filter-chip input').forEach(x=>x.checked=false);$('#search').value='';$('#latlon').value='';$('#pointStatus').textContent='';searchedPoint=null;pointHits=[];points.clearLayers();shown=[...rows];draw(shown,true);render()}
async function init(){try{const j=await fetch(DATA,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Dataset unavailable');return r.json()});rows=Array.isArray(j)?j:(j.rows||[]);shown=[...rows];const district=[...new Set(rows.map(r=>String(r.district||'').split('(')[0].trim()).filter(Boolean))].sort();const submit=[...new Set(rows.map(r=>cleanSubmit(r.submitType)).filter(x=>x&&x!=='-'))].sort();makeFilter($('#typeFilters'),['Normal','Medium','Large','Barbari','Business','Fast'],'f-type');makeFilter($('#districtFilters'),district,'f-district');makeFilter($('#submitFilters'),submit,'f-submit');makeFilter($('#activeFilters'),['YES','NO'],'f-active');draw(shown,true);render()}catch(e){$('#results').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
$('#check').onclick=checkPoint;$('#latlon').addEventListener('keydown',e=>{if(e.key==='Enter')checkPoint()});$('#search').addEventListener('input',render);$('#reset').onclick=reset;init();
