const STORAGE_KEY='digiexpress.dailyPlanner.v3';
const LEGACY_KEY='digiexpress.dailyPlanner.v2';
const DAY=86400000, SLOT=30, SLOT_H=44;
const DEFAULT={tasks:[],occurrenceStatus:{},deletedOccurrences:{},categories:['کاری','شخصی'],settings:{calendar:'jalali',language:'fa',workStart:'08:00',workEnd:'18:00',notifications:true},scheduled:{},snoozes:{},dismissed:{}};
let state=loadState(), currentPage='create', dailyCursor=todayISO(), editingId='', activeNotice=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const I18N={
 fa:{createTitle:'تعریف تسک',createSub:'کار جدید را تعریف کنید',tasksTitle:'لیست تسک‌ها',tasksSub:'جستجو، فیلتر و مدیریت فعالیت‌ها',dailyTitle:'برنامه روزانه',dailySub:'تسک‌ها را روی خط زمانی قرار دهید',settingsTitle:'تنظیمات',settingsSub:'تقویم، زبان، ساعات کاری، اعلان و اطلاعات',taskTitleLabel:'عنوان تسک',taskTitlePlaceholder:'عنوان فعالیت را وارد کنید',dueDate:'تاریخ انجام',priority:'اولویت',assignee:'مسئول',assigneePlaceholder:'نام مسئول',category:'دسته‌بندی',duration:'مدت تسک',minutes:'دقیقه',recurrence:'تکرار',recNone:'بدون تکرار',recDaily:'روزانه',recWeekly:'هفتگی',recCustom:'سفارشی',customRecurrence:'تکرار سفارشی',every:'هر',days:'روز',status:'وضعیت',statusTodo:'انجام نشده',statusDone:'انجام شده',statusCancelled:'لغو شده',description:'توضیحات',descriptionPlaceholder:'توضیحات تسک',clearForm:'پاک کردن فرم',saveTask:'ذخیره تسک',saveChanges:'ذخیره تغییرات',date:'تاریخ',allDates:'همه تاریخ‌ها',all:'همه',clearFilters:'پاک کردن فیلترها',categories:'دسته‌بندی‌ها',categoryPlaceholder:'نام دسته‌بندی',add:'اضافه',calendar:'تقویم',calendarType:'نوع تقویم',jalali:'شمسی',gregorian:'میلادی',language:'زبان',workingHours:'ساعت کاری',start:'شروع',end:'پایان',notifications:'اعلان‌ها',notificationsEnabled:'فعال بودن اعلان‌ها',enableBrowserNotifications:'فعال‌سازی اعلان مرورگر',notificationHelp:'شروع هر تسک و پایان زمان آن ۱۵ دقیقه قبل یادآوری می‌شود.',dataTransfer:'ورود و خروج اطلاعات',navCreate:'تعریف',navList:'لیست',navDaily:'روزانه',navSettings:'تنظیمات',today:'امروز',clear:'پاک کردن',noAssignee:'بدون مسئول',items:'مورد',noTasks:'تسکی برای نمایش وجود ندارد.',unscheduled:'تسک‌های زمان‌بندی نشده',allScheduled:'همه تسک‌ها زمان‌بندی شده‌اند.',priorityWord:'اولویت',ends:'پایان',deleteTask:'این تسک حذف شود؟',deleteOccurrence:'فقط این تکرار از تسک حذف شود؟',taskEdited:'تسک ویرایش شد',taskAdded:'تسک اضافه شد',titleRequired:'عنوان تسک لازم است',atLeastCategory:'حداقل یک دسته‌بندی لازم است',holidayJalali:'تعطیلات ثابت رسمی شمسی در تقویم روزانه مشخص می‌شوند.',holidayOff:'نمایش تعطیلات رسمی شمسی در حالت تقویم شمسی فعال است.',browserUnsupported:'اعلان مرورگر پشتیبانی نمی‌شود',browserEnabled:'اعلان مرورگر فعال شد',browserDenied:'مجوز اعلان داده نشد',startNotice:'شروع تسک نزدیک است',endNotice:'پایان تسک نزدیک است',minutesLeft:'۱۵ دقیقه مانده',imported:'تسک وارد شد',importFailed:'Import ناموفق'},
 en:{createTitle:'Create Task',createSub:'Define a new task',tasksTitle:'Task List',tasksSub:'Search, filter and manage tasks',dailyTitle:'Daily Plan',dailySub:'Place tasks on the daily timeline',settingsTitle:'Settings',settingsSub:'Calendar, language, working hours, notifications and data',taskTitleLabel:'Task title',taskTitlePlaceholder:'Enter task title',dueDate:'Due date',priority:'Priority',assignee:'Assignee',assigneePlaceholder:'Assignee name',category:'Category',duration:'Duration',minutes:'minutes',recurrence:'Recurrence',recNone:'No repeat',recDaily:'Daily',recWeekly:'Weekly',recCustom:'Custom',customRecurrence:'Custom repeat',every:'Every',days:'days',status:'Status',statusTodo:'Not done',statusDone:'Done',statusCancelled:'Cancelled',description:'Description',descriptionPlaceholder:'Task description',clearForm:'Clear form',saveTask:'Save task',saveChanges:'Save changes',date:'Date',allDates:'All dates',all:'All',clearFilters:'Clear filters',categories:'Categories',categoryPlaceholder:'Category name',add:'Add',calendar:'Calendar',calendarType:'Calendar type',jalali:'Jalali',gregorian:'Gregorian',language:'Language',workingHours:'Working hours',start:'Start',end:'End',notifications:'Notifications',notificationsEnabled:'Enable notifications',enableBrowserNotifications:'Enable browser notifications',notificationHelp:'You will be reminded 15 minutes before task start and task end.',dataTransfer:'Import / Export',navCreate:'Create',navList:'List',navDaily:'Daily',navSettings:'Settings',today:'Today',clear:'Clear',noAssignee:'No assignee',items:'items',noTasks:'No tasks to display.',unscheduled:'Unscheduled tasks',allScheduled:'All tasks are scheduled.',priorityWord:'Priority',ends:'Ends',deleteTask:'Delete this task?',deleteOccurrence:'Delete only this occurrence?',taskEdited:'Task updated',taskAdded:'Task added',titleRequired:'Task title is required',atLeastCategory:'At least one category is required',holidayJalali:'Fixed official Jalali holidays are marked in the daily calendar.',holidayOff:'Official Jalali holidays are shown when Jalali calendar is active.',browserUnsupported:'Browser notifications are not supported',browserEnabled:'Browser notifications enabled',browserDenied:'Notification permission was not granted',startNotice:'Task starts soon',endNotice:'Task ends soon',minutesLeft:'15 minutes remaining',imported:'tasks imported',importFailed:'Import failed'}
};
function tr(k){return (I18N[state.settings.language]||I18N.fa)[k]||k}
function deepClone(x){return JSON.parse(JSON.stringify(x))}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY)||'{}';const v=Object.assign(deepClone(DEFAULT),JSON.parse(raw));v.settings=Object.assign({},DEFAULT.settings,v.settings||{});v.deletedOccurrences=v.deletedOccurrences||{};return v}catch{return deepClone(DEFAULT)}}
function saveState(render=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));if(render)renderAll()}
function uid(){return crypto.randomUUID?crypto.randomUUID():'t'+Date.now()+Math.random().toString(36).slice(2)}
function pad(n){return String(n).padStart(2,'0')}
function todayISO(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseISO(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d,12)}
function diffDays(a,b){return Math.round((parseISO(a)-parseISO(b))/DAY)}
function addDays(s,n){const d=parseISO(s);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function div(a,b){return ~~(a/b)} function mod(a,b){return a-div(a,b)*b}
function jalCal(jy){const breaks=[-61,9,38,199,426,686,756,818,1111,1181,1210,1635,2060,2097,2192,2262,2324,2394,2456,3178];let gy=jy+621,leapJ=-14,jp=breaks[0],jm,jump,n;if(jy<jp||jy>=breaks[breaks.length-1])return{gy,march:20,leap:0};for(let i=1;i<breaks.length;i++){jm=breaks[i];jump=jm-jp;if(jy<jm)break;leapJ+=div(jump,33)*8+div(mod(jump,33),4);jp=jm}n=jy-jp;leapJ+=div(n,33)*8+div(mod(n,33)+3,4);if(mod(jump,33)===4&&jump-n===4)leapJ++;const leapG=div(gy,4)-div((div(gy,100)+1)*3,4)-150,march=20+leapJ-leapG;if(jump-n<6)n=n-jump+div(jump+4,33)*33;let leap=mod(mod(n+1,33)-1,4);if(leap===-1)leap=4;return{gy,march,leap}}
function g2d(gy,gm,gd){let d=div((gy+div(gm-8,6)+100100)*1461,4)+div(153*mod(gm+9,12)+2,5)+gd-34840408;d=d-div(div(gy+100100+div(gm-8,6),100)*3,4)+752;return d}
function d2g(jdn){let j=4*jdn+139361631;j=j+div(div(4*jdn+183187720,146097)*3,4)*4-3908;const i=div(mod(j,1461),4)*5+308;return{gd:div(mod(i,153),5)+1,gm:mod(div(i,153),12)+1,gy:div(j,1461)-100100+div(8-mod(div(i,153),12)-1,6)}}
function j2d(jy,jm,jd){const r=jalCal(jy);return g2d(r.gy,3,r.march)+(jm-1)*31-div(jm,7)*(jm-7)+jd-1}
function d2j(jdn){const g=d2g(jdn),jy=g.gy-621,r=jalCal(jy),jdn1f=g2d(g.gy,3,r.march);let k=jdn-jdn1f,jm,jd;if(k>=0){if(k<=185){jm=1+div(k,31);jd=mod(k,31)+1;return{jy,jm,jd}}k-=186}else{return d2j(jdn)}jm=7+div(k,30);jd=mod(k,30)+1;return{jy,jm,jd}}
function isoToJParts(s){const d=parseISO(s);return d2j(g2d(d.getFullYear(),d.getMonth()+1,d.getDate()))}
function jPartsToISO(y,m,d){const g=d2g(j2d(y,m,d));return `${g.gy}-${pad(g.gm)}-${pad(g.gd)}`}
function isoToJ(s){const j=isoToJParts(s);return `${j.jy}/${pad(j.jm)}/${pad(j.jd)}`}
function inputToISO(v){v=String(v||'').trim().replace(/-/g,'/');if(!v)return'';const m=v.match(/^(\d{4})[\/]?(\d{1,2})[\/]?(\d{1,2})$/);if(!m)throw Error('Invalid date');if(state.settings.calendar==='gregorian')return `${m[1]}-${pad(m[2])}-${pad(m[3])}`;return jPartsToISO(+m[1],+m[2],+m[3])}
function isoToInput(s){return state.settings.calendar==='jalali'?isoToJ(s):s.replace(/-/g,'/')}
function locale(){return state.settings.language==='en'?'en-US':'fa-IR'}
function formatDate(s,weekday=false){const d=parseISO(s),cal=state.settings.calendar==='jalali'?'persian':'gregory';return new Intl.DateTimeFormat(`${locale()}-u-ca-${cal}`,weekday?{weekday:'long',year:'numeric',month:'long',day:'numeric'}:{year:'numeric',month:'long',day:'numeric'}).format(d)}
function weekday(s){return new Intl.DateTimeFormat(locale(),{weekday:'long'}).format(parseISO(s))}
const fixedHolidays={'01/01':'نوروز','01/02':'نوروز','01/03':'نوروز','01/04':'نوروز','01/12':'روز جمهوری اسلامی','01/13':'روز طبیعت','03/14':'رحلت امام خمینی','03/15':'قیام ۱۵ خرداد','11/22':'پیروزی انقلاب اسلامی','12/29':'ملی شدن صنعت نفت'};
function holidayName(iso){if(state.settings.calendar!=='jalali')return'';const j=isoToJ(iso).split('/');return fixedHolidays[`${j[1]}/${j[2]}`]||''}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.remove('hidden');clearTimeout(x._t);x._t=setTimeout(()=>x.classList.add('hidden'),2500)}
function occurrenceKey(t,date){return `${t.id}|${date}`}
function taskOccursOn(t,date){if(!t.date||date<t.date)return false;if(!t.recurrence||t.recurrence==='none')return date===t.date;const dd=diffDays(date,t.date);if(t.recurrence==='daily')return dd>=0;if(t.recurrence==='weekly')return dd>=0&&dd%7===0;if(t.recurrence==='custom')return dd>=0&&dd%Math.max(1,Number(t.repeatEvery)||1)===0;return date===t.date}
function occurrenceStatus(t,date){return state.occurrenceStatus[occurrenceKey(t,date)]||t.status||'todo'}
function setOccurrenceStatus(t,date,status){state.occurrenceStatus[occurrenceKey(t,date)]=status;saveState()}
function occurrenceRows(rangeStart,rangeEnd){const rows=[];for(const t of state.tasks){if(!t.date)continue;for(let cur=t.date;cur<=rangeEnd;cur=addDays(cur,1)){if(cur>=rangeStart&&taskOccursOn(t,cur)&&!state.deletedOccurrences[occurrenceKey(t,cur)])rows.push({task:t,date:cur,status:occurrenceStatus(t,cur)});if(!t.recurrence||t.recurrence==='none')break}}return rows}
function priorityRank(p){return Number(p)||3} function statusRank(s){return s==='todo'?0:s==='done'?1:2}
function dueClass(date,status){if(status!=='todo')return'';const n=diffDays(date,todayISO());if(n<=1)return'urgent-red';if(n<=3)return'urgent-orange';return''}
function applyLanguage(){document.documentElement.lang=state.settings.language;document.documentElement.dir=state.settings.language==='fa'?'rtl':'ltr';$$('[data-i18n]').forEach(el=>el.textContent=tr(el.dataset.i18n));$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=tr(el.dataset.i18nPlaceholder));$('#languageSetting')&&($('#languageSetting').value=state.settings.language);$('#snoozeNotice').textContent=state.settings.language==='fa'?'تعویق ۱۰ دقیقه':'Snooze 10 min';$('#dismissNotice').textContent=state.settings.language==='fa'?'رد کردن':'Dismiss'}
function renderHeader(){const map={create:['createTitle','createSub'],tasks:['tasksTitle','tasksSub'],daily:['dailyTitle','dailySub'],settings:['settingsTitle','settingsSub']},k=map[currentPage];$('#pageTitle').textContent=tr(k[0]);$('#pageSubtitle').textContent=tr(k[1]);$('#headerDate').textContent=formatDate(todayISO(),true)}
function navigate(page){currentPage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.target===page));renderHeader();if(page==='tasks')renderTaskList();if(page==='daily')renderDaily();if(page==='settings')renderSettings()}
function renderCategories(){const sel=$('#taskCategory'),old=sel.value;sel.innerHTML=state.categories.map(c=>`<option>${esc(c)}</option>`).join('');if(old&&state.categories.includes(old))sel.value=old;$('#categoryList').innerHTML=state.categories.map(c=>`<span class="chip">${esc(c)}<button data-remove-cat="${esc(c)}">×</button></span>`).join('');$$('[data-remove-cat]').forEach(b=>b.onclick=()=>{if(state.categories.length<=1)return toast(tr('atLeastCategory'));state.categories=state.categories.filter(x=>x!==b.dataset.removeCat);saveState()})}
function resetForm(){editingId='';$('#taskId').value='';$('#taskTitle').value='';$('#taskDate').value=isoToInput(todayISO());$('#taskPriority').value='2';$('#taskAssignee').value='';$('#taskDuration').value='60';$('#taskRecurrence').value='none';$('#taskRepeatEvery').value='2';$('#taskStatus').value='todo';$('#taskDescription').value='';$('#customRepeatWrap').classList.add('hidden');$('#saveTask').textContent=tr('saveTask')}
function editTask(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;editingId=id;$('#taskId').value=id;$('#taskTitle').value=t.title||'';$('#taskDate').value=isoToInput(t.date);$('#taskPriority').value=t.priority||'2';$('#taskAssignee').value=t.assignee||'';$('#taskCategory').value=t.category||state.categories[0];$('#taskDuration').value=t.duration||60;$('#taskRecurrence').value=t.recurrence||'none';$('#taskRepeatEvery').value=t.repeatEvery||2;$('#taskStatus').value=t.status||'todo';$('#taskDescription').value=t.description||'';$('#customRepeatWrap').classList.toggle('hidden',t.recurrence!=='custom');$('#saveTask').textContent=tr('saveChanges');navigate('create')}
$('#taskForm').onsubmit=e=>{e.preventDefault();try{const obj={id:editingId||uid(),title:$('#taskTitle').value.trim(),date:inputToISO($('#taskDate').value),priority:$('#taskPriority').value,assignee:$('#taskAssignee').value.trim(),category:$('#taskCategory').value,duration:Math.max(15,Number($('#taskDuration').value)||60),recurrence:$('#taskRecurrence').value,repeatEvery:Math.max(1,Number($('#taskRepeatEvery').value)||1),status:$('#taskStatus').value,description:$('#taskDescription').value.trim(),updatedAt:new Date().toISOString()};if(!obj.title)throw Error(tr('titleRequired'));if(editingId){const i=state.tasks.findIndex(x=>x.id===editingId);obj.createdAt=state.tasks[i]?.createdAt||obj.updatedAt;state.tasks[i]=obj}else{obj.createdAt=obj.updatedAt;state.tasks.push(obj)}saveState();toast(editingId?tr('taskEdited'):tr('taskAdded'));resetForm();navigate('tasks')}catch(err){toast(err.message)}};
$('#taskRecurrence').onchange=()=>$('#customRepeatWrap').classList.toggle('hidden',$('#taskRecurrence').value!=='custom');$('#resetTask').onclick=resetForm;
function deleteOccurrence(id,date){const t=state.tasks.find(x=>x.id===id);if(!t)return;if(t.recurrence&&t.recurrence!=='none'){if(!confirm(tr('deleteOccurrence')))return;state.deletedOccurrences[occurrenceKey(t,date)]=true;delete state.scheduled[occurrenceKey(t,date)];delete state.occurrenceStatus[occurrenceKey(t,date)]}else{if(!confirm(tr('deleteTask')))return;state.tasks=state.tasks.filter(x=>x.id!==id);delete state.scheduled[occurrenceKey(t,date)]}saveState()}
function recurrenceLabel(t){return t.recurrence==='daily'?tr('recDaily'):t.recurrence==='weekly'?tr('recWeekly'):t.recurrence==='custom'?`${tr('every')} ${t.repeatEvery} ${tr('days')}`:''}
function taskCard(r){const t=r.task,st=r.status;return `<article class="task-card p${t.priority} ${dueClass(r.date,st)} ${st}"><input class="task-check" type="checkbox" data-check="${t.id}" data-date="${r.date}" ${st==='done'?'checked':''} ${st==='cancelled'?'disabled':''}><div><div class="task-name">${esc(t.title)}</div><div class="task-meta"><span>${esc(formatDate(r.date))}</span><span>${esc(t.assignee||tr('noAssignee'))}</span><span>${esc(t.category||'')}</span><span>${t.duration} ${tr('minutes')}</span><span class="badge priority-${t.priority}">${tr('priorityWord')} ${t.priority}</span>${t.recurrence!=='none'?`<span class="badge">${esc(recurrenceLabel(t))}</span>`:''}</div>${t.description?`<div class="task-meta">${esc(t.description)}</div>`:''}<select class="status-select" data-status="${t.id}" data-date="${r.date}"><option value="todo" ${st==='todo'?'selected':''}>${tr('statusTodo')}</option><option value="done" ${st==='done'?'selected':''}>${tr('statusDone')}</option><option value="cancelled" ${st==='cancelled'?'selected':''}>${tr('statusCancelled')}</option></select></div><div class="task-actions"><button data-edit="${t.id}" title="Edit">✎</button><button data-delete="${t.id}" data-delete-date="${r.date}" title="Delete">×</button></div></article>`}
function renderTaskList(){let start='2000-01-01',end='2100-12-31';try{if($('#filterDate').value.trim()){start=end=inputToISO($('#filterDate').value)}}catch{}let rows=occurrenceRows(start,end),fa=$('#filterAssignee').value,fp=$('#filterPriority').value,fs=$('#filterStatus').value;rows=rows.filter(r=>(!fa||r.task.assignee===fa)&&(!fp||r.task.priority===fp)&&(!fs||r.status===fs));rows.sort((a,b)=>statusRank(a.status)-statusRank(b.status)||(a.status==='todo'?(a.date.localeCompare(b.date)||priorityRank(a.task.priority)-priorityRank(b.task.priority)):b.date.localeCompare(a.date)));$('#taskCount').textContent=`${rows.length} ${tr('items')}`;$('#taskList').innerHTML=rows.length?rows.slice(0,1500).map(taskCard).join(''):`<div class="panel" style="padding:18px;text-align:center;color:var(--muted)">${tr('noTasks')}</div>`;bindTaskActions()}
function bindTaskActions(){$$('[data-check]').forEach(x=>x.onchange=()=>{const t=state.tasks.find(t=>t.id===x.dataset.check);if(t)setOccurrenceStatus(t,x.dataset.date,x.checked?'done':'todo')});$$('[data-status]').forEach(x=>x.onchange=()=>{const t=state.tasks.find(t=>t.id===x.dataset.status);if(t)setOccurrenceStatus(t,x.dataset.date,x.value)});$$('[data-edit]').forEach(x=>x.onclick=()=>editTask(x.dataset.edit));$$('[data-delete]').forEach(x=>x.onclick=()=>deleteOccurrence(x.dataset.delete,x.dataset.deleteDate))}
function refreshAssignees(){const vals=[...new Set(state.tasks.map(t=>t.assignee).filter(Boolean))].sort(),old=$('#filterAssignee').value;$('#filterAssignee').innerHTML=`<option value="">${tr('all')}</option>`+vals.map(x=>`<option>${esc(x)}</option>`).join('');if(vals.includes(old))$('#filterAssignee').value=old}
['filterAssignee','filterPriority','filterStatus'].forEach(id=>$('#'+id).oninput=renderTaskList);$('#clearFilters').onclick=()=>{$('#filterDate').value='';$('#filterAssignee').value='';$('#filterPriority').value='';$('#filterStatus').value='';renderTaskList()};
function timeToMin(s){const[a,b]=String(s).split(':').map(Number);return a*60+b} function minToTime(m){return `${pad(Math.floor(m/60))}:${pad(m%60)}`}
function renderDaily(){const rows=occurrenceRows(dailyCursor,dailyCursor).filter(r=>r.status!=='cancelled');$('#dailyDate').textContent=formatDate(dailyCursor);$('#dailyWeekday').textContent=weekday(dailyCursor)+(holidayName(dailyCursor)?` • ${holidayName(dailyCursor)}`:'');const scheduled=rows.filter(r=>state.scheduled[occurrenceKey(r.task,r.date)]),free=rows.filter(r=>!state.scheduled[occurrenceKey(r.task,r.date)]);$('#unscheduled').innerHTML=`<h3>${tr('unscheduled')}</h3><div class="unscheduled-list">${free.length?free.map(r=>`<div class="unscheduled-task p${r.task.priority}" draggable="true" data-drag-task="${r.task.id}" data-drag-date="${r.date}"><strong>${esc(r.task.title)}</strong><small>${r.task.duration} ${tr('minutes')} • ${tr('priorityWord')} ${r.task.priority}</small></div>`).join(''):`<span class="muted">${tr('allScheduled')}</span>`}</div>`;const start=timeToMin(state.settings.workStart),end=timeToMin(state.settings.workEnd);let html='';for(let m=start;m<end;m+=SLOT){const slot=minToTime(m),items=scheduled.filter(r=>state.scheduled[occurrenceKey(r.task,r.date)]===slot);html+=`<div class="timeline-row"><div class="timeline-time">${slot}</div><div class="timeline-slot" data-slot="${slot}">${items.map(r=>{const dur=Math.max(15,Number(r.task.duration)||60),height=Math.max(36,(dur/SLOT)*SLOT_H-6),endTime=minToTime(Math.min(24*60,m+dur));return `<div class="timeline-task p${r.task.priority}" style="height:${height}px" data-timeline-task="${r.task.id}"><input type="checkbox" data-daily-check="${r.task.id}" data-date="${r.date}" ${r.status==='done'?'checked':''}><div class="grow"><strong>${esc(r.task.title)}</strong><small>${dur} ${tr('minutes')} • ${tr('ends')} ${endTime}</small></div><button data-unschedule="${r.task.id}" data-date="${r.date}" title="Unschedule">×</button></div>`}).join('')}</div></div>`}$('#timeline').innerHTML=html;$$('[data-drag-task]').forEach(x=>x.ondragstart=e=>e.dataTransfer.setData('text/plain',JSON.stringify({id:x.dataset.dragTask,date:x.dataset.dragDate})));$$('.timeline-slot').forEach(s=>{s.ondragover=e=>{e.preventDefault();s.classList.add('dragover')};s.ondragleave=()=>s.classList.remove('dragover');s.ondrop=e=>{e.preventDefault();s.classList.remove('dragover');try{const x=JSON.parse(e.dataTransfer.getData('text/plain'));state.scheduled[`${x.id}|${x.date}`]=s.dataset.slot;saveState()}catch{}}});$$('[data-daily-check]').forEach(x=>x.onchange=()=>{const t=state.tasks.find(t=>t.id===x.dataset.dailyCheck);if(t)setOccurrenceStatus(t,x.dataset.date,x.checked?'done':'todo')});$$('[data-unschedule]').forEach(x=>x.onclick=()=>{delete state.scheduled[`${x.dataset.unschedule}|${x.dataset.date}`];saveState()})}
$('#prevDay').onclick=()=>{dailyCursor=addDays(dailyCursor,-1);renderDaily()};$('#nextDay').onclick=()=>{dailyCursor=addDays(dailyCursor,1);renderDaily()};
function renderSettings(){renderCategories();$('#calendarSetting').value=state.settings.calendar;$('#languageSetting').value=state.settings.language;$('#workStart').value=state.settings.workStart;$('#workEnd').value=state.settings.workEnd;$('#notificationsEnabled').checked=!!state.settings.notifications;$('#holidayInfo').textContent=state.settings.calendar==='jalali'?tr('holidayJalali'):tr('holidayOff')}
$('#addCategory').onclick=()=>{const v=$('#newCategory').value.trim();if(!v)return;if(!state.categories.includes(v))state.categories.push(v);$('#newCategory').value='';saveState()};$('#calendarSetting').onchange=()=>{state.settings.calendar=$('#calendarSetting').value;saveState();resetForm()};$('#languageSetting').onchange=()=>{state.settings.language=$('#languageSetting').value;saveState();applyLanguage();renderAll()};$('#workStart').onchange=()=>{state.settings.workStart=$('#workStart').value||'08:00';saveState()};$('#workEnd').onchange=()=>{state.settings.workEnd=$('#workEnd').value||'18:00';saveState()};$('#notificationsEnabled').onchange=async()=>{const enabled=$('#notificationsEnabled').checked;state.settings.notifications=enabled;saveState();if(enabled&&'Notification' in window&&Notification.permission==='default'){try{const p=await Notification.requestPermission();toast(p==='granted'?tr('browserEnabled'):tr('browserDenied'))}catch{}}};
function monthDaysJ(y,m){if(m<=6)return31;if(m<=11)return30;return jalCal(y).leap===0?30:29}
function setupDatePicker(inputSel,buttonSel,pickerSel,{allowClear=false,onChange=null}={}){
 const input=$(inputSel),button=$(buttonSel),picker=$(pickerSel);let cursor=todayISO();
 function selectedISO(){try{return input.value?inputToISO(input.value):todayISO()}catch{return todayISO()}}
 function close(){picker.classList.add('hidden');picker.classList.remove('open')}
 function place(){const r=(button||input).getBoundingClientRect(),w=Math.min(310,Math.max(260,window.innerWidth-28));picker.style.width=w+'px';let left=Math.max(14,Math.min(window.innerWidth-w-14,r.left));let top=r.bottom+8;if(top+390>window.innerHeight)top=Math.max(14,r.top-390);picker.style.left=left+'px';picker.style.top=top+'px'}
 function render(){cursor=cursor||selectedISO();const sel=selectedISO(),jal=state.settings.calendar==='jalali';let year,month,days,firstISO;if(jal){const p=isoToJParts(cursor);year=p.jy;month=p.jm;days=monthDaysJ(year,month);firstISO=jPartsToISO(year,month,1)}else{const d=parseISO(cursor);year=d.getFullYear();month=d.getMonth()+1;days=new Date(year,month,0).getDate();firstISO=`${year}-${pad(month)}-01`}const jsDay=parseISO(firstISO).getDay(),weekStart=state.settings.language==='fa'?6:0,offset=(jsDay-weekStart+7)%7;const weekdays=state.settings.language==='fa'?['ش','ی','د','س','چ','پ','ج']:['S','M','T','W','T','F','S'];let cells='';for(let i=0;i<offset;i++)cells+='<span></span>';for(let d=1;d<=days;d++){const iso=jal?jPartsToISO(year,month,d):`${year}-${pad(month)}-${pad(d)}`,holiday=holidayName(iso)?' holiday':'';cells+=`<button type="button" data-pick="${iso}" class="${sel===iso?'selected':''}${holiday}">${d}</button>`}picker.innerHTML=`<div class="date-picker-head"><button type="button" data-prev>‹</button><strong>${jal?`${year}/${pad(month)}`:new Intl.DateTimeFormat(locale(),{month:'long',year:'numeric'}).format(new Date(year,month-1,1))}</strong><button type="button" data-next>›</button></div><div class="date-picker-week">${weekdays.map(x=>`<span>${x}</span>`).join('')}</div><div class="date-picker-days">${cells}</div><div class="date-picker-foot"><button type="button" data-today>${tr('today')}</button>${allowClear?`<button type="button" data-clear>${tr('clear')}</button>`:''}</div>`;
  picker.querySelector('[data-prev]').onclick=e=>{e.stopPropagation();if(jal){month--;if(month<1){month=12;year--}cursor=jPartsToISO(year,month,1)}else{const x=new Date(year,month-2,1);cursor=`${x.getFullYear()}-${pad(x.getMonth()+1)}-01`}render();place()};
  picker.querySelector('[data-next]').onclick=e=>{e.stopPropagation();if(jal){month++;if(month>12){month=1;year++}cursor=jPartsToISO(year,month,1)}else{const x=new Date(year,month,1);cursor=`${x.getFullYear()}-${pad(x.getMonth()+1)}-01`}render();place()};
  picker.querySelector('[data-today]').onclick=e=>{e.stopPropagation();input.value=isoToInput(todayISO());cursor=todayISO();close();onChange&&onChange()};
  picker.querySelector('[data-clear]')?.addEventListener('click',e=>{e.stopPropagation();input.value='';close();onChange&&onChange()});
  picker.querySelectorAll('[data-pick]').forEach(b=>b.onclick=e=>{e.stopPropagation();input.value=isoToInput(b.dataset.pick);cursor=b.dataset.pick;close();onChange&&onChange()})
 }
 function open(e){e&&e.stopPropagation();$$('.date-picker.open').forEach(x=>{if(x!==picker){x.classList.add('hidden');x.classList.remove('open')}});cursor=selectedISO();render();picker.classList.remove('hidden');picker.classList.add('open');place()}
 button.addEventListener('click',open);input.addEventListener('click',open);input.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(e)}});
 picker.addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',e=>{if(!picker.contains(e.target)&&e.target!==button&&e.target!==input)close()});window.addEventListener('resize',()=>{if(picker.classList.contains('open'))place()});
}
function exportExcel(){const cols=['Title','Date','Priority','Assignee','Category','Duration','Recurrence','Repeat Every','Status','Description','Start Time'];const rows=state.tasks.map(t=>[t.title,t.date,t.priority,t.assignee,t.category,t.duration,t.recurrence,t.repeatEvery,t.status,t.description,state.scheduled[`${t.id}|${t.date}`]||'']);const escx=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');const table=`<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"></head><body><table><tr>${cols.map(x=>`<th>${x}</th>`).join('')}</tr>${rows.map(r=>`<tr>${r.map(x=>`<td>${escx(x)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([table],{type:'application/vnd.ms-excel'}));a.download=`Daily_Planner_${todayISO()}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$('#exportExcel').onclick=exportExcel;
async function unzipXlsx(file){const u=new Uint8Array(await file.arrayBuffer()),dv=new DataView(u.buffer);let e=-1;for(let i=u.length-22;i>=Math.max(0,u.length-66000);i--)if(dv.getUint32(i,true)===0x06054b50){e=i;break}if(e<0)throw Error('Invalid Excel');const count=dv.getUint16(e+10,true),off=dv.getUint32(e+16,true),dec=new TextDecoder();let p=off,out={};for(let n=0;n<count;n++){if(dv.getUint32(p,true)!==0x02014b50)break;const method=dv.getUint16(p+10,true),size=dv.getUint32(p+20,true),nl=dv.getUint16(p+28,true),el=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),lo=dv.getUint32(p+42,true),name=dec.decode(u.subarray(p+46,p+46+nl)),ln=dv.getUint16(lo+26,true),le=dv.getUint16(lo+28,true),data=u.subarray(lo+30+ln+le,lo+30+ln+le+size);if(method===0)out[name]=data;else if(method===8){const ds=new DecompressionStream('deflate-raw');out[name]=new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer())}p+=46+nl+el+cl}return out}
async function readImport(file){if(file.name.toLowerCase().endsWith('.csv')){const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean),parse=l=>l.split(',').map(x=>x.replace(/^"|"$/g,'').replace(/""/g,'"'));return{headers:parse(lines.shift()||''),rows:lines.map(parse)}}const z=await unzipXlsx(file),parser=new DOMParser(),dec=new TextDecoder();let shared=[];if(z['xl/sharedStrings.xml'])shared=[...parser.parseFromString(dec.decode(z['xl/sharedStrings.xml']),'text/xml').getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(x=>x.textContent).join(''));const sk=Object.keys(z).find(k=>/^xl\/worksheets\/sheet\d+\.xml$/.test(k));if(!sk)throw Error('Sheet not found');const doc=parser.parseFromString(dec.decode(z[sk]),'text/xml'),raw=[];function ci(r){const m=r.match(/^([A-Z]+)/);let n=0;for(const c of m[1])n=n*26+c.charCodeAt(0)-64;return n-1}for(const rr of [...doc.getElementsByTagName('row')]){const a=[];for(const c of [...rr.getElementsByTagName('c')]){const i=ci(c.getAttribute('r')),t=c.getAttribute('t');let v=t==='inlineStr'?[...c.getElementsByTagName('t')].map(x=>x.textContent).join(''):(c.getElementsByTagName('v')[0]?.textContent||'');if(t==='s')v=shared[+v]||'';a[i]=v}raw.push(a)}return{headers:raw.shift()||[],rows:raw}}
$('#importExcel').onchange=async e=>{try{const x=await readImport(e.target.files[0]),map=Object.fromEntries(x.headers.map((h,i)=>[String(h).trim().toLowerCase(),i])),g=(r,...ks)=>{for(const k of ks)if(map[k]!=null)return r[map[k]]??'';return''};let n=0;for(const r of x.rows){const title=g(r,'title','عنوان');if(!title)continue;const date=String(g(r,'date','تاریخ')||todayISO()).replace(/\//g,'-');state.tasks.push({id:uid(),title,date,priority:String(g(r,'priority','اولویت')||2),assignee:g(r,'assignee','مسئول'),category:g(r,'category','دسته بندی')||state.categories[0],duration:Number(g(r,'duration','مدت')||60),recurrence:g(r,'recurrence','تکرار')||'none',repeatEvery:Number(g(r,'repeat every')||1),status:g(r,'status','وضعیت')||'todo',description:g(r,'description','توضیحات'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});n++}saveState();toast(`${n} ${tr('imported')}`)}catch(err){toast(`${tr('importFailed')}: ${err.message}`)}e.target.value=''};
function noticeFor(task,date,kind){const key=`${task.id}|${date}|${kind}`,title=kind==='start'?tr('startNotice'):tr('endNotice'),text=`${task.title} • ${tr('minutesLeft')}`;activeNotice={key,task,date,kind};$('#notificationTitle').textContent=title;$('#notificationText').textContent=text;$('#notificationBox').classList.remove('hidden');if(state.settings.notifications&&'Notification'in window&&Notification.permission==='granted')try{new Notification(title,{body:text,tag:key})}catch{}}
function checkNotifications(){if(!state.settings.notifications)return;const now=new Date(),date=todayISO(),minutes=now.getHours()*60+now.getMinutes();for(const r of occurrenceRows(date,date)){const t=r.task,start=state.scheduled[occurrenceKey(t,date)];if(!start||r.status!=='todo')continue;const sm=timeToMin(start),em=sm+Number(t.duration||60);for(const[k,target]of[['start',sm-15],['end',em-15]]){const key=`${t.id}|${date}|${k}`,snooze=Number(state.snoozes[key]||0);if(state.dismissed[key]||snooze>Date.now())continue;if(Math.abs(minutes-target)<=0.5)noticeFor(t,date,k)}}}
$('#snoozeNotice').onclick=()=>{if(activeNotice)state.snoozes[activeNotice.key]=Date.now()+10*60000;$('#notificationBox').classList.add('hidden');saveState(false);activeNotice=null};$('#dismissNotice').onclick=()=>{if(activeNotice)state.dismissed[activeNotice.key]=true;$('#notificationBox').classList.add('hidden');saveState(false);activeNotice=null};
function renderAll(){applyLanguage();renderCategories();refreshAssignees();renderHeader();if(currentPage==='tasks')renderTaskList();if(currentPage==='daily')renderDaily();if(currentPage==='settings')renderSettings()}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.target));
setupDatePicker('#taskDate','#taskDateButton','#taskDatePicker');setupDatePicker('#filterDate','#filterDateButton','#filterDatePicker',{allowClear:true,onChange:renderTaskList});
applyLanguage();resetForm();renderAll();setInterval(checkNotifications,30000);checkNotifications();
