const DATA='../data/DX_Polygons.xlsx?v=226';
const TYPE_MAP={Normal:1,Medium:2,Large:3,Barbari:4,Business:5,Fast:6};
let polygons=[];let currentLayers=[];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const map=L.map('map').setView([32,51],6),polyLayer=L.layerGroup().addTo(map),pointLayer=L.layerGroup().addTo(map);
const TILE_TIMEOUT_MS=15000,tilePending=new Map();let tileSeq=0;
window.addEventListener('message',event=>{if(event.source!==parent)return;const d=event.data||{};if(d.type!=='DIGIEXPRESS_RESOURCE_RESULT')return;const p=tilePending.get(String(d.requestId||''));if(!p)return;tilePending.delete(String(d.requestId||''));clearTimeout(p.timer);d.ok&&d.dataUrl?p.resolve(d.dataUrl):p.reject(new Error(d.error||'Tile request failed'));});
function requestTileFromHost(url){return new Promise((resolve,reject)=>{const requestId='tile-'+Date.now()+'-'+(++tileSeq),timer=setTimeout(()=>{tilePending.delete(requestId);reject(new Error('Tile bridge timeout'));},TILE_TIMEOUT_MS);tilePending.set(requestId,{resolve,reject,timer});parent.postMessage({type:'DIGIEXPRESS_FETCH_RESOURCE',requestId,url},'*');});}
const DigiexpressTileLayer=L.TileLayer.extend({createTile(coords,done){const tile=document.createElement('img');tile.alt='';const url=this.getTileUrl(coords);requestTileFromHost(url).then(dataUrl=>{tile.onload=()=>done(null,tile);tile.onerror=()=>done(new Error('Tile decode failed'),tile);tile.src=dataUrl;}).catch(err=>done(err,tile));return tile;}});
new DigiexpressTileLayer('https://osm.digiexpress.ir/tile/{z}/{x}/{y}.png',{maxZoom:19,keepBuffer:2,updateWhenIdle:true}).addTo(map);
function natureLabel(n){return Object.entries(TYPE_MAP).find(([,v])=>Number(v)===Number(n))?.[0]||String(n??'-')}
function polyColor(n){return ({1:'#1976d2',2:'#16a34a',3:'#7c3aed',4:'#F79009',5:'#d946ef',6:'#0891b2'})[Number(n)]||'#64748b'}
function selectedTypes(){const checked=[...document.querySelectorAll('.type-check:checked')].map(x=>x.value);if(checked.includes('All')||!checked.length)return Object.keys(TYPE_MAP);return checked;}
function matchesPoint(lat,lon,types){const wanted=new Set(types.map(t=>TYPE_MAP[t]));const pt=turf.point([lon,lat]);const out={};for(const t of types)out[t]=[];for(const r of polygons){if(!wanted.has(Number(r.natureId)))continue;const hit=(r.coordinates||[]).some(part=>{try{return turf.booleanPointInPolygon(pt,turf.polygon([[...part.map(c=>[c[1],c[0]])]]));}catch(_){return false;}});if(hit){const t=natureLabel(r.natureId);(out[t]||(out[t]=[])).push(r);}}return out;}
function drawSingle(lat,lon,result){polyLayer.clearLayers();pointLayer.clearLayers();L.marker([lat,lon]).addTo(pointLayer);currentLayers=[];for(const [type,rows] of Object.entries(result))for(const r of rows)for(const part of (r.coordinates||[])){const p=L.polygon(part,{color:polyColor(r.natureId),weight:4,fillOpacity:.25}).addTo(polyLayer);p.bindPopup(`<b>${esc(r.name)}</b><br>ID: ${esc(r.dcId)}<br>${esc(type)}`);currentLayers.push(p);}const b=L.featureGroup([...currentLayers,...pointLayer.getLayers()]).getBounds();if(b.isValid())map.fitBounds(b,{padding:[20,20]});else map.setView([lat,lon],14);setTimeout(()=>map.invalidateSize(),50);}
function renderSingle(lat,lon,result){const rows=[];for(const [type,items] of Object.entries(result)){if(items.length){for(const r of items)rows.push([type,r.name,r.dcId,r.iata||'']);}else rows.push([type,'Not found','','']);}$('#results').innerHTML=`<table><thead><tr><th>Type</th><th>Parent Name</th><th>DC ID</th><th>IATA</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;const hits=rows.filter(r=>r[1]!=='Not found').length;$('#resultStatus').textContent=hits?`${hits} matching parent record(s).`:'No parent found.';$('#resultStatus').className='status '+(hits?'ok':'error');drawSingle(lat,lon,result);}
function parseLocation(text){const p=String(text||'').split(',').map(x=>Number(x.trim()));if(p.length!==2||p.some(x=>!Number.isFinite(x))||p[0]<-90||p[0]>90||p[1]<-180||p[1]>180)throw new Error('Use format: latitude, longitude');return{lat:p[0],lon:p[1]};}
function readPointRows(file){return file.arrayBuffer().then(buf=>{const wb=XLSX.read(buf,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});if(!aoa.length)return[];let start=0;const a=Number(aoa[0]?.[0]),b=Number(aoa[0]?.[1]);if(!Number.isFinite(a)||!Number.isFinite(b))start=1;return aoa.slice(start).filter(r=>String(r?.[0]??'').trim()||String(r?.[1]??'').trim());});}
function makeFilters(){const vals=['All',...Object.keys(TYPE_MAP)];$('#typeFilters').innerHTML=vals.map(v=>`<label class="filter-chip"><input class="type-check" type="checkbox" value="${v}" ${v==='All'?'checked':''}><span>${v}</span></label>`).join('');const boxes=[...document.querySelectorAll('.type-check')],all=boxes[0];boxes.forEach(b=>b.onchange=()=>{if(b===all&&b.checked)boxes.slice(1).forEach(x=>x.checked=false);else if(b!==all&&b.checked)all.checked=false;if(!boxes.some(x=>x.checked))all.checked=true;});}
async function determineSingle(){try{const {lat,lon}=parseLocation($('#location').value),types=selectedTypes(),result=matchesPoint(lat,lon,types);renderSingle(lat,lon,result);}catch(e){$('#resultStatus').textContent=e.message;$('#resultStatus').className='status error';}}
async function processExcel(){const file=$('#locationsFile').files?.[0];if(!file){$('#resultStatus').textContent='Select an Excel file first.';$('#resultStatus').className='status error';return;}try{$('#processExcel').disabled=true;$('#resultStatus').textContent='Reading locations…';const pts=await readPointRows(file),types=selectedTypes();if(!pts.length)throw new Error('No latitude/longitude rows were found.');const headers=['Latitude','Longitude','Status'];for(const t of types)headers.push(`${t} Parent Name`,`${t} DC ID`);const output=[];for(let i=0;i<pts.length;i++){const lat=Number(pts[i][0]),lon=Number(pts[i][1]),row=[pts[i][0],pts[i][1]];if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180){row.push('Invalid coordinate');for(const t of types)row.push('','');output.push(row);continue;}const result=matchesPoint(lat,lon,types),any=types.some(t=>(result[t]||[]).length);row.push(any?'Matched':'No parent found');for(const t of types){const ms=result[t]||[];row.push(ms.length?ms.map(x=>x.name).filter(Boolean).join(' | '):'Not found',ms.length?ms.map(x=>x.dcId).filter(x=>x!==''&&x!=null).join(' | '):'');}output.push(row);if(i%25===0){$('#resultStatus').textContent=`Processing ${i+1} / ${pts.length}…`;await new Promise(r=>setTimeout(r,0));}}
const ws=XLSX.utils.aoa_to_sheet([headers,...output]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Parent Determination');const stamp=new Date().toISOString().slice(0,10).replace(/-/g,'');XLSX.writeFile(wb,`parent_determination_${stamp}.xlsx`);$('#resultStatus').textContent=`Completed: ${output.length} location(s). Excel downloaded.`;$('#resultStatus').className='status ok';$('#results').innerHTML=`<table><thead><tr>${headers.slice(0,5).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${output.slice(-100).map(r=>`<tr>${r.slice(0,5).map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}catch(e){$('#resultStatus').textContent=e.message||String(e);$('#resultStatus').className='status error';}finally{$('#processExcel').disabled=false;}}
async function init(){makeFilters();document.querySelectorAll('input[name=mode]').forEach(r=>r.onchange=()=>{$('#singlePanel').classList.toggle('hidden',r.value==='excel'&&r.checked);$('#excelPanel').classList.toggle('hidden',r.value==='single'&&r.checked);setTimeout(()=>map.invalidateSize(),50);});$('#determine').onclick=determineSingle;$('#location').onkeydown=e=>{if(e.key==='Enter')determineSingle();};$('#processExcel').onclick=processExcel;try{const ds=await DXPolygonLoader.load(DATA);polygons=ds.rows||[];$('#datasetStatus').textContent=`Loaded ${polygons.length} polygons directly from DX_Polygons.xlsx.`;$('#datasetStatus').className='status ok';const all=L.featureGroup();for(const r of polygons.slice(0,80))for(const part of (r.coordinates||[]))L.polygon(part,{opacity:0,fillOpacity:0}).addTo(all);const b=all.getBounds();if(b.isValid())map.fitBounds(b,{padding:[12,12]});}catch(e){$('#datasetStatus').textContent=e.message;$('#datasetStatus').className='status error';}}
window.addEventListener('resize',()=>map.invalidateSize());document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(()=>map.invalidateSize(),50);});init();
