const K='digiexpress.workHealthy.v1',D={enabled:true,interval:45,duration:45,start:'08:00',end:'18:00',groups:['eyes','neck','shoulders','back','wrists','legs'],nextAt:0};
let s=Object.assign({},D,JSON.parse(localStorage.getItem(K)||'{}')),active=null,countTimer=null;
const $=q=>document.querySelector(q),save=()=>localStorage.setItem(K,JSON.stringify(s));
const ex=[
 ['eyes','20-20-20 Eyes','Look at a distant point for 20 seconds. Keep your face relaxed and blink slowly.'],
 ['neck','Neck Rotation','Keep shoulders relaxed. Turn your head gently left, return to center, then turn right.'],
 ['shoulders','Shoulder Rolls','Lift both shoulders toward your ears, roll them backward, then let them drop down.'],
 ['back','Seated Back Extension','Sit tall. Open your chest and lean back gently without forcing the lower back.'],
 ['wrists','Wrist Stretch','Extend one arm and gently draw the fingers back. Switch sides halfway through.'],
 ['legs','Calf Raises','Stand tall, rise slowly onto your toes, pause briefly, then lower with control.']
];
function frame(content){return `<div class="motion-stage"><svg viewBox="0 0 320 210" role="img" aria-label="Animated exercise demonstration">${content}</svg></div>`}
function basePerson(extra='',group='',withHead=true){return `<g class="${group}"><circle class="pulse" cx="160" cy="78" r="52"/>${withHead?'<circle class="head" cx="160" cy="48" r="23" stroke-width="4"/>':''}<rect class="torso" x="130" y="76" width="60" height="70" rx="26" stroke-width="4"/><path class="limb" d="M136 92 L100 123"/><path class="limb" d="M184 92 L220 123"/><path class="limb" d="M145 142 L132 187"/><path class="limb" d="M175 142 L188 187"/><circle class="joint" cx="100" cy="123" r="6"/><circle class="joint" cx="220" cy="123" r="6"/>${extra}</g>`}
function animationSvg(kind){
 if(kind==='eyes')return frame(`<circle cx="160" cy="105" r="72" fill="none" stroke="var(--violet)" stroke-width="4" opacity=".25"/>${basePerson(`<g class="blink"><ellipse cx="151" cy="46" rx="7" ry="5" fill="#fff"/><ellipse cx="169" cy="46" rx="7" ry="5" fill="#fff"/><circle class="eye-dot" cx="151" cy="46" r="3"/><circle class="eye-dot" cx="169" cy="46" r="3"/></g>`,'sway')}<path class="motion-path moving-arrow" d="M72 48 H112 M208 48 H248"/><polygon class="arrow" points="72,48 86,39 86,57"/><polygon class="arrow" points="248,48 234,39 234,57"/>`);
 if(kind==='neck')return frame(`${basePerson('','',false)}<g class="head-turn"><circle class="head" cx="160" cy="48" r="23" stroke-width="4"/><path d="M151 48h18" stroke="#7C4A03" stroke-width="4" stroke-linecap="round"/></g><path class="motion-path moving-arrow" d="M105 42 Q160 6 215 42"/><polygon class="arrow" points="104,42 119,36 115,52"/><polygon class="arrow" points="216,42 201,36 205,52"/>`);
 if(kind==='shoulders')return frame(`<g class="shoulder-roll">${basePerson('','')}</g><path class="motion-path moving-arrow" d="M92 102 Q92 65 125 70 M228 102 Q228 65 195 70"/><polygon class="arrow" points="124,70 111,62 110,78"/><polygon class="arrow" points="196,70 209,62 210,78"/>`);
 if(kind==='back')return frame(`<rect class="chair" x="112" y="130" width="96" height="16" rx="7" stroke-width="3"/><path class="chair" d="M120 145v45M200 145v45" stroke-width="8"/><g class="back-open">${basePerson('<path class="limb" d="M135 90 Q160 70 185 90"/>','')}</g><path class="motion-path moving-arrow" d="M230 110 Q252 80 233 51"/><polygon class="arrow" points="234,50 225,64 242,62"/>`);
 if(kind==='wrists')return frame(`${basePerson('','')}<g class="wrist-left"><path class="limb" d="M100 123 L62 104"/><path d="M62 104 l-7 -20 M62 104 l8 -19 M62 104 l19 -11" stroke="var(--pink)" stroke-width="5" stroke-linecap="round"/></g><g class="wrist-right"><path class="limb" d="M220 123 L258 104"/><path d="M258 104 l7 -20 M258 104 l-8 -19 M258 104 l-19 -11" stroke="var(--green)" stroke-width="5" stroke-linecap="round"/></g><path class="motion-path moving-arrow" d="M50 144 Q70 161 91 142 M270 144 Q250 161 229 142"/>`);
 return frame(`<g class="calf">${basePerson('','')}</g><path class="motion-path moving-arrow" d="M112 190 V151 M208 190 V151"/><polygon class="arrow" points="112,150 103,166 121,166"/><polygon class="arrow" points="208,150 199,166 217,166"/><ellipse cx="132" cy="192" rx="24" ry="7" fill="var(--green)" opacity=".35"/><ellipse cx="188" cy="192" rx="24" ry="7" fill="var(--green)" opacity=".35"/>`);
}
function render(){for(const id of['interval','duration','start','end'])$('#'+id).value=s[id];$('#enabled').checked=s.enabled;$('#groups').innerHTML=ex.map(e=>`<label><input type="checkbox" data-g="${e[0]}" ${s.groups.includes(e[0])?'checked':''}> ${e[1]}</label>`).join('');$('#library').innerHTML=ex.map(e=>`<div class="tile">${animationSvg(e[0])}<strong>${e[1]}</strong><p>${e[2]}</p></div>`).join('');updateNext()}
function withinHours(){const n=new Date(),m=n.getHours()*60+n.getMinutes(),tm=x=>{const[a,b]=x.split(':').map(Number);return a*60+b};return m>=tm(s.start)&&m<=tm(s.end)}
function schedule(){if(!s.nextAt||s.nextAt<Date.now())s.nextAt=Date.now()+s.interval*60000;save();updateNext()}
function updateNext(){if(!s.enabled){$('#next').textContent='Reminders are disabled.';return}const mins=Math.max(0,Math.ceil((s.nextAt-Date.now())/60000));$('#next').textContent=`Next reminder in about ${mins} minute(s).`}
function pick(){const list=ex.filter(e=>s.groups.includes(e[0]));return list[Math.floor(Math.random()*list.length)]||ex[0]}
function showExercise(){active=pick();$('#picture').innerHTML=animationSvg(active[0]);$('#title').textContent=active[1];$('#text').textContent=active[2];$('#modal').classList.remove('hidden');let sec=s.duration;$('#count').textContent=`${sec}s`;clearInterval(countTimer);countTimer=setInterval(()=>{sec--;$('#count').textContent=`${Math.max(0,sec)}s`;if(sec<=0)clearInterval(countTimer)},1000);try{if(Notification.permission==='granted')new Notification('Work Healthy',{body:active[1]})}catch{}}
setInterval(()=>{if(s.enabled&&withinHours()&&Date.now()>=s.nextAt){showExercise();s.nextAt=Date.now()+s.interval*60000;save()}updateNext()},30000);
$('#save').onclick=()=>{s.interval=Math.max(15,Number($('#interval').value)||45);s.duration=Math.max(15,Number($('#duration').value)||45);s.start=$('#start').value||'08:00';s.end=$('#end').value||'18:00';s.groups=[...document.querySelectorAll('[data-g]:checked')].map(x=>x.dataset.g);s.enabled=$('#enabled').checked;s.nextAt=Date.now()+s.interval*60000;save();render()};
$('#enabled').onchange=()=>{s.enabled=$('#enabled').checked;s.nextAt=Date.now()+s.interval*60000;save();updateNext()};$('#showNow').onclick=showExercise;$('#done').onclick=()=>{$('#modal').classList.add('hidden');clearInterval(countTimer);schedule()};$('#snooze').onclick=()=>{$('#modal').classList.add('hidden');clearInterval(countTimer);s.nextAt=Date.now()+10*60000;save();updateNext()};$('#close').onclick=()=>{$('#modal').classList.add('hidden');clearInterval(countTimer)};schedule();render();
